### ISSUE TITLE
Panic while committing a block

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/fabric-peer-ext#310]
peer0.org1.example.com    | 2019-11-16 16:32:31.959 UTC [gossip.state] func1 -> ERRO 0ca Got error while committing(block number should have been 10 but was 11
peer0.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/blkstorage/cdbblkstorage.(*cdbBlockStore).validateBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext@v0.0.0-20191116153307-f307ce023d53/pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go:103
peer0.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/blkstorage/cdbblkstorage.(*cdbBlockStore).AddBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext@v0.0.0-20191116153307-f307ce023d53/pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go:77
peer0.org1.example.com    | github.com/hyperledger/fabric/core/ledger/ledgerstorage.(*Store).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/ledger/ledgerstorage/store.go:141
peer0.org1.example.com    | github.com/hyperledger/fabric/core/ledger/kvledger.(*kvLedger).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/ledger/kvledger/kv_ledger.go:341
peer0.org1.example.com    | github.com/hyperledger/fabric/core/committer.(*LedgerCommitter).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/committer/committer_impl.go:89
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*coordinator).StoreBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/privdata/coordinator.go:269
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:131
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | commit failed
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*coordinator).StoreBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/privdata/coordinator.go:272
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:131
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:132
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337)
peer0.org1.example.com    | 2019-11-16 16:32:31.976 UTC [gossip.state] commitBlock -> ERRO 0cb Got error while committing(block number should have been 10 but was 11
peer0.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/blkstorage/cdbblkstorage.(*cdbBlockStore).validateBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext@v0.0.0-20191116153307-f307ce023d53/pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go:103
peer0.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/blkstorage/cdbblkstorage.(*cdbBlockStore).AddBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext@v0.0.0-20191116153307-f307ce023d53/pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go:77
peer0.org1.example.com    | github.com/hyperledger/fabric/core/ledger/ledgerstorage.(*Store).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/ledger/ledgerstorage/store.go:141
peer0.org1.example.com    | github.com/hyperledger/fabric/core/ledger/kvledger.(*kvLedger).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/ledger/kvledger/kv_ledger.go:341
peer0.org1.example.com    | github.com/hyperledger/fabric/core/committer.(*LedgerCommitter).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/committer/committer_impl.go:89
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*coordinator).StoreBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/privdata/coordinator.go:269
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:131
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | commit failed
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*coordinator).StoreBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/privdata/coordinator.go:272
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:131
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:901
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337)
peer0.org1.example.com    | 2019-11-16 16:32:31.986 UTC [gossip.state] deliverPayloads -> PANI 0cc Cannot commit block to the ledger due to block number should have been 10 but was 11
peer0.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/blkstorage/cdbblkstorage.(*cdbBlockStore).validateBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext@v0.0.0-20191116153307-f307ce023d53/pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go:103
peer0.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/blkstorage/cdbblkstorage.(*cdbBlockStore).AddBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext@v0.0.0-20191116153307-f307ce023d53/pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go:77
peer0.org1.example.com    | github.com/hyperledger/fabric/core/ledger/ledgerstorage.(*Store).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/ledger/ledgerstorage/store.go:141
peer0.org1.example.com    | github.com/hyperledger/fabric/core/ledger/kvledger.(*kvLedger).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/ledger/kvledger/kv_ledger.go:341
peer0.org1.example.com    | github.com/hyperledger/fabric/core/committer.(*LedgerCommitter).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/committer/committer_impl.go:89
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*coordinator).StoreBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/privdata/coordinator.go:269
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:131
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | commit failed
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*coordinator).StoreBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/privdata/coordinator.go:272
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:131
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:693
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | panic: Cannot commit block to the ledger due to block number should have been 10 but was 11
peer0.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/blkstorage/cdbblkstorage.(*cdbBlockStore).validateBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext@v0.0.0-20191116153307-f307ce023d53/pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go:103
peer0.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/blkstorage/cdbblkstorage.(*cdbBlockStore).AddBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext@v0.0.0-20191116153307-f307ce023d53/pkg/blkstorage/cdbblkstorage/cdb_blkstorage.go:77
peer0.org1.example.com    | github.com/hyperledger/fabric/core/ledger/ledgerstorage.(*Store).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/ledger/ledgerstorage/store.go:141
peer0.org1.example.com    | github.com/hyperledger/fabric/core/ledger/kvledger.(*kvLedger).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/ledger/kvledger/kv_ledger.go:341
peer0.org1.example.com    | github.com/hyperledger/fabric/core/committer.(*LedgerCommitter).CommitWithPvtData
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/core/committer/committer_impl.go:89
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*coordinator).StoreBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/privdata/coordinator.go:269
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:131
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | commit failed
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*coordinator).StoreBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/privdata/coordinator.go:272
peer0.org1.example.com    | github.com/hyperledger/fabric/extensions/gossip/state.(*gossipStateProviderExtension).StoreBlock.func1
peer0.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-peer-ext/mod/peer@v0.0.0-20191116153307-f307ce023d53/gossip/state/state.go:131
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).commitBlock
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:900
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:688
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:693
peer0.org1.example.com    | runtime.goexit
peer0.org1.example.com    | 	/usr/local/go/src/runtime/asm_amd64.s:1337
peer0.org1.example.com    | 
peer0.org1.example.com    | goroutine 785 [running]:
peer0.org1.example.com    | go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc007f00840, 0x0, 0x0, 0x0)
peer0.org1.example.com    | 	/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:229 +0x546
peer0.org1.example.com    | go.uber.org/zap.(*SugaredLogger).log(0xc000010a08, 0xc002221e04, 0x1a322a4, 0x2c, 0xc001c1b0f0, 0x1, 0x1, 0x0, 0x0, 0x0)
peer0.org1.example.com    | 	/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:234 +0x101
peer0.org1.example.com    | go.uber.org/zap.(*SugaredLogger).Panicf(...)
peer0.org1.example.com    | 	/go/pkg/mod/go.uber.org/zap@v1.10.0/sugar.go:159
peer0.org1.example.com    | github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(0xc000010a10, 0x1a322a4, 0x2c, 0xc001c1b0f0, 0x1, 0x1)
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/common/flogging/zap.go:74 +0x7d
peer0.org1.example.com    | github.com/hyperledger/fabric/gossip/state.(*GossipStateProviderImpl).deliverPayloads(0xc001bf35f0)
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:693 +0x503
peer0.org1.example.com    | created by github.com/hyperledger/fabric/gossip/state.NewGossipStateProvider
peer0.org1.example.com    | 	/go/pkg/mod/github.com/trustbloc/fabric-mod@v0.1.1-0.20191115184302-84db05f49385/gossip/state/state.go:368 +0x958
pe

**Comment by bstasyszyn** [comment]
Fixed by #312
