### ISSUE TITLE
Non-committing peer returns error on private data pull request

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/fabric-peer-ext#549]
Following is the error:

peer1.org1.example.com    | 2020-12-22 21:40:41.232 UTC [cachedpvtdatastore] GetPvtDataByBlockNum -> WARN 1e9 [mychannel] Block out of range. Last committed block=1, block requested=29
peer1.org1.example.com    | goroutine 378 [running]:
peer1.org1.example.com    | runtime/debug.Stack(0x0, 0x0, 0x0)
peer1.org1.example.com    | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
peer1.org1.example.com    | runtime/debug.PrintStack()
peer1.org1.example.com    | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
peer1.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/pvtdatastorage/cachedpvtdatastore.(*store).GetPvtDataByBlockNum(0xc001cdf7c0, 0x1d, 0xc0024cb5c0, 0x203000, 0x203000, 0x203000, 0xc0024b5780, 0x5)
peer1.org1.example.com    | 	/go/src/trustbloc/fabric-peer-ext/pkg/pvtdatastorage/cachedpvtdatastore/store_impl.go:145 +0x24f
peer1.org1.example.com    | github.com/trustbloc/fabric-peer-ext/pkg/pvtdatastorage.(*pvtDataStore).GetPvtDataByBlockNum(0xc002586e40, 0x1d, 0xc0024cb5c0, 0x1e45f00, 0x30, 0x30, 0x98, 0x98)
peer1.org1.example.com    | 	/go/src/trustbloc/fabric-peer-ext/pkg/pvtdatastorage/store_impl.go:103 +0x4c
peer1.org1.example.com    | github.com/hyperledger/fabric/core/ledger/kvledger.(*kvLedger).GetPvtDataByNum(0xc000481550, 0x1d, 0xc0024cb5c0, 0x0, 0x0, 0x0, 0x0, 0x0)
peer1.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-mod@v0.0.0-20201222161848-39d8b4fadcd8/core/ledger/kvledger/kv_ledger.go:660 +0xaa
peer1.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*dataRetriever).fromLedger(0xc0026f63a0, 0xc003a489e8, 0x1, 0x1, 0x1d, 0xc003a489e8, 0xbcb07d, 0x1)
peer1.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-mod@v0.0.0-20201222161848-39d8b4fadcd8/gossip/privdata/dataretriever.go:101 +0x1d9
peer1.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*dataRetriever).CollectionRWSet(0xc0026f63a0, 0xc003a489e8, 0x1, 0x1, 0x1d, 0xc000000076, 0xc1c510, 0xc003c53db0, 0xbc59c6)
peer1.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-mod@v0.0.0-20201222161848-39d8b4fadcd8/gossip/privdata/dataretriever.go:88 +0x3f8
peer1.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*puller).createResponse(0xc001ddd880, 0x2291f60, 0xc003251b00, 0x0, 0x0, 0x0)
peer1.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-mod@v0.0.0-20201222161848-39d8b4fadcd8/gossip/privdata/pull.go:159 +0x29b
peer1.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*puller).handleRequest(0xc001ddd880, 0x2291f60, 0xc003251b00)
peer1.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-mod@v0.0.0-20201222161848-39d8b4fadcd8/gossip/privdata/pull.go:138 +0x1bb
peer1.org1.example.com    | github.com/hyperledger/fabric/gossip/privdata.(*puller).listen(0xc001ddd880)
peer1.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-mod@v0.0.0-20201222161848-39d8b4fadcd8/gossip/privdata/pull.go:124 +0x199
peer1.org1.example.com    | created by github.com/hyperledger/fabric/gossip/privdata.NewPuller
peer1.org1.example.com    | 	/go/pkg/mod/github.com/bstasyszyn/fabric-mod@v0.0.0-20201222161848-39d8b4fadcd8/gossip/privdata/pull.go:105 +0x201
peer1.org1.example.com    | 2020-12-22 21:40:41.232 UTC [gossip.privdata] createResponse -> WARN 1ea could not obtain private collection rwset for block 29, because of wasn't able to obtain private data, block sequence number 29, due to Last committed bloc

**Comment by bstasyszyn** [comment]
This is a duplicate of #547
